# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 6.0.0'

gem 'pg', '>= 0.18', '< 2.0'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'faraday', '~> 0.15.4'
gem 'httpclient', '~> 2.8.3'
gem 'oj'
gem 'puma', '~> 4.3'
# gem 'bcrypt', '~> 3.1.7'
# gem 'image_processing', '~> 1.2'

gem 'attr_encrypted', '~> 3.1.0'
gem 'connection_pool', '~> 2.2.2'
gem 'nio4r', '~> 2.5'
gem 'rack-cors'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.8'
end

group :development do
  gem 'guard-rspec', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'faker', '~> 2.4.0'
  gem 'ruby-jmeter', require: false
end

group :test do
  gem 'webmock'
end
