default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: encryptor_backend_client_development
  username: <%= ENV.fetch('PGUSER') %>
  password: <%= ENV.fetch('PGPASSWORD') %>
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  port: <%= ENV.fetch('PGPORT', 5432) %>

test:
  <<: *default
  database: encryptor_backend_client_test

production:
  <<: *default
  database: encryptor_backend_client_production
  username: encryptor_backend_client
  password: <%= ENV['ENCRYPTOR_BACKEND_CLIENT_DATABASE_PASSWORD'] %>
