version: '3.7'

services:
  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=tcc_caio
      - POSTGRES_PASSWORD=tcc_caio
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  encryptor:
    build:
      context: ./encryptor_umbrella
    depends_on:
      - postgres
    environment:
      PGUSER: tcc_caio
      PGPASSWORD: tcc_caio
      PGPORT: 5432
      PGHOST: postgres
      ENCRYPTOR_URL: encryptor
      DATABASE_URL: postgres://tcc_caio:tcc_caio@postgres:5432/encryptor_dev
      SECRET_KEY_BASE: encryptor_dev
    networks:
      - backend
    volumes:
      - ./encryptor_umbrella:/opt/app
    ports:
      - 4000:4000
  encryptor_client:
    build:
      context: ./encryptor_client
    depends_on:
      - postgres
      - encryptor
    environment:
      PGUSER: tcc_caio
      PGPASSWORD: tcc_caio
      PGPORT: 5432
      PGHOST: postgres
      ENCRYPTOR_URL: http://encryptor:4000
    links:
      - encryptor
      - postgres
    networks:
      - backend
    volumes:
      - ./encryptor_client:/opt/app
      - gems:/bundle
    ports:
      - 3000:3000

volumes:
  gems:
  postgres_data:

networks:
  backend:
    driver: bridge
