version: '3.7'

services:
  postgres:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=tcc_caio
      - POSTGRES_PASSWORD=tcc_caio
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  remote_encryptor:
    build:
      context: ./remote_encryptor
    networks:
      - backend
    volumes:
      - ./remote_encryptor:/opt/app
    environment:
      TCP_PORT: 4444
    ports:
      - 4444:4444
  encryptor_client:
    build:
      context: ./encryptor_client
    depends_on:
      - postgres
      - remote_encryptor
    environment:
      PGUSER: tcc_caio
      PGPASSWORD: tcc_caio
      PGPORT: 5432
      PGHOST: postgres
      ENCRYPTOR_HOST: remote_encryptor
      ENCRYPTOR_PORT: 4444
    links:
      - remote_encryptor
      - postgres
    networks:
      - backend
    volumes:
      - ./encryptor_client:/opt/app
      - gems:/bundle
    ports:
      - 3000:3000

volumes:
  gems:
  postgres_data:

networks:
  backend:
    driver: bridge
