default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tcc_caio
  password: tcc_caio
  host: postgres
  port: 5432

development:
  <<: *default
  database: encryptor_client_development_small
  <%#database: encryptor_client_development_medium%>
  <%#database: encryptor_client_development_large%>

test:
  <<: *default
  database: encryptor_client_test

production:
  <<: *default
  database: encryptor_client_production
  url: <%= ENV['DATABASE_URL'] %>
